name: CI Pipeline
on:
  push:
    branches:
      - 'main'

jobs:
  ci_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit 🛒
        uses: actions/checkout@v4 # can handle checkout from fork PRs as well

      - name: Print something
        run: echo "Hello World"
